sudo: required
install:
- wget https://github.com/spf13/hugo/releases/download/v0.19/hugo_0.19-64bit.deb
- sudo dpkg -i hugo_0.19-64bit.deb
- sudo pip install Pygments
script:
- hugo
after_success:
- bash deploy.sh

