sudo: required
install:
- wget https://github.com/spf13/hugo/releases/download/v0.17/hugo_0.17-64bit.deb
- sudo dpkg -i hugo_0.17-64bit.deb
- sudo pip install Pygments
script:
- hugo
after_success:
- bash deploy.sh
env:
  global:
    secure: osir9PFPBi3ruaMqTD/aHq60FG23k6sys/fHRcB7fafN32JK1pJTzpkJhTgGvca3Vd0lPQN/ZEnYaQk+YGUgPnUC7nIQnGaKl4sRCeaprUGXYlCVmYLAYg8RziMp797WRFzC//1CKs9rHXsGWfOfDAy8CMWf/VkrmSLXFCNhNmzedG9fjKfNRS/s/YzvC6ua9WKHJcoPYpty0w36/MukIlUo31GTzg1jvcBqkmEYENjWnbN8MVkN8VikMz/HHqF+jERiDEt4kaRplUIPcFj4MJLXggySWK2ldOhWH+u2FunBa/OmCVQVbLpzrpVxdoqTYOjRl8HNSt4ijCQPaJHddWeYrY3XvSBPk5oooNHe8lfGX3Lpd/fHAZCH0vu6OPn4p3k4zPuUOEMFimpcyig+4MLGye+D3v5V6uH8+hZ/MFObjgbvGEQKYl+nh8806ubZjdRuGVVt30iyyfRotifovaflsYFcqivW7FF5WQQuFaG5OxUC+BwTHtHqkwyDz1Yoczsc1aj51F/ynCPUWErWzMkDzsNjU8DA6GApr6NOlxl1f0l3rZBPVMzRirnb2cELXPiFmCdy32tePQTxhfWRuPubjDbLMZMWeCbs7k0ailVpl4Oucna7eZcUNvVP6SsSuPFhoib7NYnto+7E1yJxli89gwT5Gu1SjMq2KsNTCOg=
