language: go
sudo: required
cache:
  directories:
  - "$HOME/gopath/src/github.com/bep"
  - "$HOME/gopath/src/github.com/BurntSushi"
  - "$HOME/gopath/src/github.com/cpuguy83"
  - "$HOME/gopath/src/github.com/dchest"
  - "$HOME/gopath/src/github.com/eknkc"
  - "$HOME/gopath/src/github.com/fsnotify"
  - "$HOME/gopath/src/github.com/gorilla"
  - "$HOME/gopath/src/github.com/hashicorp"
  - "$HOME/gopath/src/github.com/kardianos"
  - "$HOME/gopath/src/github.com/kr"
  - "$HOME/gopath/src/github.com/kyokomi"
  - "$HOME/gopath/src/github.com/list"
  - "$HOME/gopath/src/github.com/magiconair"
  - "$HOME/gopath/src/github.com/miekg"
  - "$HOME/gopath/src/github.com/mitchellh"
  - "$HOME/gopath/src/github.com/nicksnyder"
  - "$HOME/gopath/src/github.com/pelletier"
  - "$HOME/gopath/src/github.com/pkg"
  - "$HOME/gopath/src/github.com/PuerkitoBio"
  - "$HOME/gopath/src/github.com/russross"
  - "$HOME/gopath/src/github.com/shurcooL"
  - "$HOME/gopath/src/github.com/spf13"
  - "$HOME/gopath/src/github.com/yosssi"
  - "$HOME/gopath/src/golang.org"
  - "$HOME/gopath/src/gopkg.in"
  - "$HOME/gopath/pkg/"
  - "$HOME/gopath/bin/"

install: 
    - sudo pip install Pygments
    - go get -v github.com/spf13/hugo
script:
  - hugo -v
