sudo: required
install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.30.2/hugo_0.30.2_Linux-64bit.deb
- sudo dpkg -i hugo_0.30.2_Linux-64bit.deb

script:
- hugo
after_success:
- bash deploy.sh

