baseurl = "http://arapaima.uk"
title = "Arapaima (UK)"
theme = "lanyon-hugo"
PygmentsCodeFences = "true"
PygmentsStyle = "lovelace"
[Params]
    DateForm =  "2006-01-02"
    Title = "arapaima.uk"
    Tagline =  "Data, Databases, Delivery"
    Author  = "Gavin Campbell"

[taxonomies]
    tag = "tags"