languageCode = "en-gb"
baseurl = "http://arapaima.uk/"
title = "Arapaima (UK)"
theme = "lanyon-hugo"
PygmentsCodeFences = "true"
PygmentsStyle = "lovelace"

[params]
    DateForm =  "2006-_1-_2"
    Title = "arapaima.uk"
    Tagline =  "Data, Databases, Delivery"
    Author  = "Gavin Campbell"

[taxonomies]
    tag = "tags"